#!/bin/sh
# build TQGG - compile and link
gfortran -c -fdefault-real-8 -Wall ../../src/dataio/MainArrays.f90
gfortran -c -fdefault-real-8 -Wall ../../src/gridgen/*.f
gfortran -c -fdefault-real-8 -Wall ../../src/gridgen/*.f90
gfortran -c -fdefault-real-8 -Wall ../../src/plotsubs/*.f
gfortran -c -fdefault-real-8 -Wall ../../src/plotsubs/*.f90
gfortran -c -fdefault-real-8 -Wall ../../src/PigInterface/*.f90
gfortran -c -fdefault-real-8 -Wall ../../src/gridedit/*.f
gfortran -c -fdefault-real-8 -Wall ../../src/gridedit/*.f90
gfortran -c -fdefault-real-8 -Wall ../../src/dataio/*.f
gfortran -c -fdefault-real-8 -Wall ../../src/dataio/*.f90
gfortran -c -fdefault-real-8 -Wall ../../src/Xm_dialogs/*.f90
gfortran -c -fdefault-real-8 -Wall ../../src/XMotif/*.f90
gcc -c -Wall ../../src/XMotif/XmMain.c
gcc -c -Wall ../../src/XMotif/XmDrawdbl.c
gcc -c -Wall ../../src/XMotif/XmDialogs.c
gfortran *.o  -o TQGG -lXm -lXt -lX11
rm *.o
